import os
import openai

with open("api_key.txt") as file:
    openai.api_key = file.read()

# openai.api_key = os.getenv("OPENAI_API_KEY")

# None type if it returns an error


def get_api_reponse(prompt: str, verbose: bool = False) -> str | None:
    """ 
    Returns the text generated by the API. 
    promt : str = The text to prompt the API with.
    verbose : bool = Whether or not to print the entire response.
    """
    text: str | None = None

    try:
        response = openai.Completion.create(
            model="text-davinci-003",
            prompt=prompt,
            temperature=0.9,        # The higher it is, the more random the answer will be
            # 1 token is approximately 4 characters or 0.75 words for English text
            max_tokens=150,
            top_p=1,
            frequency_penalty=0,    # The higher it is, the less likely the AI will repeat itself
            # The higher it is, the more likely the AI will talk about new topics
            presence_penalty=0.6,
            stop=[" Human:", " AI:"]
        )

        if verbose:
            print(response)
        # NOTE: Are choices always a list with a single element that is a dict?
        choices: dict = response.get("choices")[0]
        text = choices.get("text")

    except Exception as e:
        print(f"Error:\n{e}")
        return None

    return text


if __name__ == "__main__":
    tweet = "I am a pirate."
    
    # NOTE: Use this only during testing as it will use up your API credits!!!
    # text = get_api_reponse(
    #     prompt=f"Generate a joke based on the following text:{tweet}")

    # print(f"Generated joke:\n{text}")
